// <auto-generated />
using System;
using GraduationInvite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ThiepMoiTotNghiep.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419084850_InitKhachMoi")]
    partial class InitKhachMoi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GraduationInvite.Models.KhachMoi", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("AnhBase64")
                        .HasColumnType("text");

                    b.Property<int?>("SoLuotGheTham")
                        .HasColumnType("integer");

                    b.Property<int?>("SoLuotIn")
                        .HasColumnType("integer");

                    b.Property<string>("TenKhachMoi")
                        .HasColumnType("text");

                    b.Property<bool?>("ThamGia")
                        .HasColumnType("boolean");

                    b.HasKey("ID");

                    b.ToTable("KhachMois");
                });
#pragma warning restore 612, 618
        }
    }
}
